apiVersion: v1
kind: Service
metadata:
  labels:
    app: selenium-hub
  name: selenium-hub
spec:
  type: NodePort
  ports:
    - name: "4442"
      port: 4442
      targetPort: 4442
    - name: "4443"
      port: 4443
      targetPort: 4443
    - protocol: TCP
      name: "4444"
      port: 4444
      targetPort: 4444
      nodePort: 30007
  selector:
    app: selenium-hub
